# Generated by Django 4.0.1 on 2022-02-05 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('N', 'Not started yet'), ('R', 'Not finished'), ('F', 'Finished')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 22, 18, 39, 999163, tzinfo=utc)),
        ),
    ]
