# Generated by Django 4.0.1 on 2022-02-03 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 17, 3, 15, 556785, tzinfo=utc)),
        ),
    ]
