# Generated by Django 4.0.1 on 2022-02-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_flashcard_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='pub_date',
        ),
    ]
